///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace seibel_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("ffa84b81-b051-40ef-9d35-c54f5bc7b65f", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the seibel_testRepository repository.
        /// </summary>
        public static seibel_testRepository repo = seibel_testRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            UserName = "QACRM0";
            Password = "{RShiftKey up}{End down}{RShiftKey down}{RShiftKey up}T{RShiftKey up}esting123";
            customer = "23559219";
            product = "Q1I8";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _UserName;

        /// <summary>
        /// Gets or sets the value of variable UserName.
        /// </summary>
        [TestVariable("4ce8b9ef-a513-4edb-a021-344d8cd9a8d9")]
        public string UserName
        {
            get { return _UserName; }
            set { _UserName = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("f0a3467d-bbef-4e3d-86cf-70faf18f8a69")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        string _customer;

        /// <summary>
        /// Gets or sets the value of variable customer.
        /// </summary>
        [TestVariable("55c15763-2135-4b0c-920a-75db099236a7")]
        public string customer
        {
            get { return _customer; }
            set { _customer = value; }
        }

        string _product;

        /// <summary>
        /// Gets or sets the value of variable product.
        /// </summary>
        [TestVariable("b808f2e2-4870-4857-9e67-84d137fb1a2e")]
        public string product
        {
            get { return _product; }
            set { _product = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.FormContent.SWEUserName' at 89;19.", repo.SiebelCallCenter.FormContent.SWEUserNameInfo, new RecordItemIndex(0));
            repo.SiebelCallCenter.FormContent.SWEUserName.Click("89;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$UserName' with focus on 'SiebelCallCenter.FormContent.SWEUserName'.", repo.SiebelCallCenter.FormContent.SWEUserNameInfo, new RecordItemIndex(1));
            repo.SiebelCallCenter.FormContent.SWEUserName.PressKeys(UserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.FormContent.SWEPassword' at 135;12.", repo.SiebelCallCenter.FormContent.SWEPasswordInfo, new RecordItemIndex(2));
            repo.SiebelCallCenter.FormContent.SWEPassword.Click("135;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'SiebelCallCenter.FormContent.SWEPassword'.", repo.SiebelCallCenter.FormContent.SWEPasswordInfo, new RecordItemIndex(3));
            repo.SiebelCallCenter.FormContent.SWEPassword.PressKeys(Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.FormContent.Login' at 54;13.", repo.SiebelCallCenter.FormContent.LoginInfo, new RecordItemIndex(4));
            repo.SiebelCallCenter.FormContent.Login.Click("54;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.Text' at 8;14.", repo.SiebelCallCenter.TextInfo, new RecordItemIndex(5));
            repo.SiebelCallCenter.Text.Click("8;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.Text' at 107;24.", repo.SiebelCallCenter.TextInfo, new RecordItemIndex(6));
            repo.SiebelCallCenter.Text.Click("107;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$customer' with focus on 'SiebelCallCenter.Text'.", repo.SiebelCallCenter.TextInfo, new RecordItemIndex(7));
            repo.SiebelCallCenter.Text.PressKeys(customer);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.ScSearch' at 78;11.", repo.SiebelCallCenter.ScSearchInfo, new RecordItemIndex(8));
            repo.SiebelCallCenter.ScSearch.Click("78;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SiebelCallCenter.BORNE' at 110;44.", repo.SiebelCallCenter.BORNEInfo, new RecordItemIndex(9));
            repo.SiebelCallCenter.BORNE.DoubleClick("110;44");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.ScSnkpkSalesorder' at 48;19.", repo.SiebelCallCenter.ScSnkpkSalesorderInfo, new RecordItemIndex(10));
            repo.SiebelCallCenter.ScSnkpkSalesorder.Click("48;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.ScSearchtext' at 179;30.", repo.SiebelCallCenter.ScSearchtextInfo, new RecordItemIndex(11));
            repo.SiebelCallCenter.ScSearchtext.Click("179;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$product' with focus on 'SiebelCallCenter.ScSearchtext'.", repo.SiebelCallCenter.ScSearchtextInfo, new RecordItemIndex(12));
            repo.SiebelCallCenter.ScSearchtext.PressKeys(product);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCSearchbutton' at 43;39.", repo.SiebelCallCenter.SCSearchbuttonInfo, new RecordItemIndex(13));
            repo.SiebelCallCenter.SCSearchbutton.Click("43;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.NewQueenDualI8360SmartBed' at 423;41.", repo.SiebelCallCenter.NewQueenDualI8360SmartBedInfo, new RecordItemIndex(14));
            repo.SiebelCallCenter.NewQueenDualI8360SmartBed.Click("423;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCAddToCart' at 70;22.", repo.SiebelCallCenter.SCAddToCartInfo, new RecordItemIndex(15));
            repo.SiebelCallCenter.SCAddToCart.Click("70;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.Next' at 25;23.", repo.SiebelCallCenter.NextInfo, new RecordItemIndex(16));
            repo.SiebelCallCenter.Next.Click("25;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.Next1' at 15;1.", repo.SiebelCallCenter.Next1Info, new RecordItemIndex(17));
            repo.SiebelCallCenter.Next1.Click("15;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.ScProceed' at 62;11.", repo.SiebelCallCenter.ScProceedInfo, new RecordItemIndex(18));
            repo.SiebelCallCenter.ScProceed.Click("62;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCShipValidateOrder' at 53;18.", repo.SiebelCallCenter.SCShipValidateOrderInfo, new RecordItemIndex(19));
            repo.SiebelCallCenter.SCShipValidateOrder.Click("53;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCProcedPayments' at 16;26.", repo.SiebelCallCenter.SCProcedPaymentsInfo, new RecordItemIndex(20));
            repo.SiebelCallCenter.SCProcedPayments.Click("16;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.ScProceed' at 78;29.", repo.SiebelCallCenter.ScProceedInfo, new RecordItemIndex(21));
            repo.SiebelCallCenter.ScProceed.Click("78;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCShipValidateOrder' at 107;20.", repo.SiebelCallCenter.SCShipValidateOrderInfo, new RecordItemIndex(22));
            repo.SiebelCallCenter.SCShipValidateOrder.Click("107;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SiebelCallCenter'", repo.SiebelCallCenter.SelfInfo, new ActionTimeout(10000), new RecordItemIndex(23));
            repo.SiebelCallCenter.SelfInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCProcedPayments' at LowerRight.", repo.SiebelCallCenter.SCProcedPaymentsInfo, new RecordItemIndex(24));
            repo.SiebelCallCenter.SCProcedPayments.Click(Location.LowerRight);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.CashPayment' at 75;18.", repo.SiebelCallCenter.CashPaymentInfo, new RecordItemIndex(25));
            repo.SiebelCallCenter.CashPayment.Click("75;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SiebelCallCenter.SCCash' at 35;21.", repo.SiebelCallCenter.SCCashInfo, new RecordItemIndex(26));
            repo.SiebelCallCenter.SCCash.Click("35;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SiebelCallCenter' at 848;124.", repo.SiebelCallCenter.SelfInfo, new RecordItemIndex(27));
            repo.SiebelCallCenter.Self.MoveTo("848;124");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SiebelCallCenter' at 856;116.", repo.SiebelCallCenter.SelfInfo, new RecordItemIndex(28));
            repo.SiebelCallCenter.Self.MoveTo("856;116");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SiebelCallCenter.Payments' at 540;-127.", repo.SiebelCallCenter.PaymentsInfo, new RecordItemIndex(29));
            repo.SiebelCallCenter.Payments.MoveTo("540;-127");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
