///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace seibel_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the seibel_testRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a951339f-6ae4-49e3-b6ae-92220619375e")]
    public partial class seibel_testRepository : RepoGenBaseFolder
    {
        static seibel_testRepository instance = new seibel_testRepository();
        seibel_testRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        seibel_testRepositoryFolders.ExplorerAppFolder _explorer;
        seibel_testRepositoryFolders.SiebelCallCenterAppFolder _siebelcallcenter;
        seibel_testRepositoryFolders.SiebelCallCenterWorkMicrosoftEdAppFolder _siebelcallcenterworkmicrosofted;
        seibel_testRepositoryFolders.LineItemsWorkMicrosoftEdgeAppFolder _lineitemsworkmicrosoftedge;
        seibel_testRepositoryFolders.LineItemsAnd1MorePageWorkMicrAppFolder _lineitemsand1morepageworkmicr;
        RepoItemInfo _donrielInfo;
        RepoItemInfo _scselectboxInfo;

        /// <summary>
        /// Gets the singleton class instance representing the seibel_testRepository element repository.
        /// </summary>
        [RepositoryFolder("a951339f-6ae4-49e3-b6ae-92220619375e")]
        public static seibel_testRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public seibel_testRepository() 
            : base("seibel_testRepository", "/", null, 0, false, "a951339f-6ae4-49e3-b6ae-92220619375e", ".\\RepositoryImages\\seibel_testRepositorya951339f.rximgres")
        {
            _applicationundertest = new seibel_testRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new seibel_testRepositoryFolders.ExplorerAppFolder(this);
            _siebelcallcenter = new seibel_testRepositoryFolders.SiebelCallCenterAppFolder(this);
            _siebelcallcenterworkmicrosofted = new seibel_testRepositoryFolders.SiebelCallCenterWorkMicrosoftEdAppFolder(this);
            _lineitemsworkmicrosoftedge = new seibel_testRepositoryFolders.LineItemsWorkMicrosoftEdgeAppFolder(this);
            _lineitemsand1morepageworkmicr = new seibel_testRepositoryFolders.LineItemsAnd1MorePageWorkMicrAppFolder(this);
            _donrielInfo = new RepoItemInfo(this, "DONRIEL", "/dom[@domain='crmappstst1.comfort.com:4443']//tr[#'row1']/?", 30000, null, "b6ace1b8-e36e-47a7-b9dd-c169701ab0db");
            _scselectboxInfo = new RepoItemInfo(this, "SCSelectBox", "/dom[@domain='crmappstst1.comfort.com:4443']//div[#'applet1']/div[1]/div[38]//select", 30000, null, "3866fde5-8c09-4d59-ab0f-8f684d65c028");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a951339f-6ae4-49e3-b6ae-92220619375e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DONRIEL item.
        /// </summary>
        [RepositoryItem("b6ace1b8-e36e-47a7-b9dd-c169701ab0db")]
        public virtual Ranorex.Unknown DONRIEL
        {
            get
            {
                 return _donrielInfo.CreateAdapter<Ranorex.Unknown>(true);
            }
        }

        /// <summary>
        /// The DONRIEL item info.
        /// </summary>
        [RepositoryItemInfo("b6ace1b8-e36e-47a7-b9dd-c169701ab0db")]
        public virtual RepoItemInfo DONRIELInfo
        {
            get
            {
                return _donrielInfo;
            }
        }

        /// <summary>
        /// The SCSelectBox item.
        /// </summary>
        [RepositoryItem("3866fde5-8c09-4d59-ab0f-8f684d65c028")]
        public virtual Ranorex.SelectTag SCSelectBox
        {
            get
            {
                 return _scselectboxInfo.CreateAdapter<Ranorex.SelectTag>(true);
            }
        }

        /// <summary>
        /// The SCSelectBox item info.
        /// </summary>
        [RepositoryItemInfo("3866fde5-8c09-4d59-ab0f-8f684d65c028")]
        public virtual RepoItemInfo SCSelectBoxInfo
        {
            get
            {
                return _scselectboxInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3131c533-2d52-4ca5-ac65-40ef972f593d")]
        public virtual seibel_testRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("77f39770-d046-44eb-a5c9-993be1f1f7dc")]
        public virtual seibel_testRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The SiebelCallCenter folder.
        /// </summary>
        [RepositoryFolder("96f804d6-44be-4277-b3d2-f9a22f62d87f")]
        public virtual seibel_testRepositoryFolders.SiebelCallCenterAppFolder SiebelCallCenter
        {
            get { return _siebelcallcenter; }
        }

        /// <summary>
        /// The SiebelCallCenterWorkMicrosoftEd folder.
        /// </summary>
        [RepositoryFolder("769ac0b0-efee-4a3b-8b19-6d12e6fcb4fe")]
        public virtual seibel_testRepositoryFolders.SiebelCallCenterWorkMicrosoftEdAppFolder SiebelCallCenterWorkMicrosoftEd
        {
            get { return _siebelcallcenterworkmicrosofted; }
        }

        /// <summary>
        /// The LineItemsWorkMicrosoftEdge folder.
        /// </summary>
        [RepositoryFolder("041fe668-8eda-49a8-b132-139bfecc127a")]
        public virtual seibel_testRepositoryFolders.LineItemsWorkMicrosoftEdgeAppFolder LineItemsWorkMicrosoftEdge
        {
            get { return _lineitemsworkmicrosoftedge; }
        }

        /// <summary>
        /// The LineItemsAnd1MorePageWorkMicr folder.
        /// </summary>
        [RepositoryFolder("2901aa33-2dec-4a92-8c06-5b9e824cacf0")]
        public virtual seibel_testRepositoryFolders.LineItemsAnd1MorePageWorkMicrAppFolder LineItemsAnd1MorePageWorkMicr
        {
            get { return _lineitemsand1morepageworkmicr; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class seibel_testRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3131c533-2d52-4ca5-ac65-40ef972f593d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "3131c533-2d52-4ca5-ac65-40ef972f593d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3131c533-2d52-4ca5-ac65-40ef972f593d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3131c533-2d52-4ca5-ac65-40ef972f593d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("77f39770-d046-44eb-a5c9-993be1f1f7dc")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _microsoftedge1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "77f39770-d046-44eb-a5c9-993be1f1f7dc", "")
            {
                _microsoftedge1runningwindowInfo = new RepoItemInfo(this, "MicrosoftEdge1RunningWindow", "container[@automationid='40965']//toolbar[@accessiblename='Running applications']/button[2]", ".//toolbar[@accessiblename='Running applications']/button[2]", 30000, null, "55965ad6-d886-44de-8084-7d4239043f86");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("77f39770-d046-44eb-a5c9-993be1f1f7dc")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77f39770-d046-44eb-a5c9-993be1f1f7dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MicrosoftEdge1RunningWindow item.
            /// </summary>
            [RepositoryItem("55965ad6-d886-44de-8084-7d4239043f86")]
            public virtual Ranorex.Button MicrosoftEdge1RunningWindow
            {
                get
                {
                    return _microsoftedge1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MicrosoftEdge1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("55965ad6-d886-44de-8084-7d4239043f86")]
            public virtual RepoItemInfo MicrosoftEdge1RunningWindowInfo
            {
                get
                {
                    return _microsoftedge1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The SiebelCallCenterAppFolder folder.
        /// </summary>
        [RepositoryFolder("96f804d6-44be-4277-b3d2-f9a22f62d87f")]
        public partial class SiebelCallCenterAppFolder : RepoGenBaseFolder
        {
            seibel_testRepositoryFolders.FormContentFolder _formcontent;
            RepoItemInfo _textInfo;
            RepoItemInfo _prof1Info;
            RepoItemInfo _scsearchInfo;
            RepoItemInfo _borneInfo;
            RepoItemInfo _contactInfo;
            RepoItemInfo _containerfluidnomarginnopaddingscInfo;
            RepoItemInfo _scsnkpksalesorderInfo;
            RepoItemInfo _scsearchtextInfo;
            RepoItemInfo _scsearchbuttonInfo;
            RepoItemInfo _newqueenduali8360smartbedInfo;
            RepoItemInfo _scaddtocartInfo;
            RepoItemInfo _nextInfo;
            RepoItemInfo _next1Info;
            RepoItemInfo _scproceedInfo;
            RepoItemInfo _scshipvalidateorderInfo;
            RepoItemInfo _scprocedpaymentsInfo;
            RepoItemInfo _cashpaymentInfo;
            RepoItemInfo _sccashInfo;
            RepoItemInfo _orginalcolorscsopanelheadInfo;
            RepoItemInfo _paymentsInfo;

            /// <summary>
            /// Creates a new SiebelCallCenter  folder.
            /// </summary>
            public SiebelCallCenterAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SiebelCallCenter", "/dom[@domain='crmappstst1.comfort.com:4443']", parentFolder, 30000, null, false, "96f804d6-44be-4277-b3d2-f9a22f62d87f", "")
            {
                _formcontent = new seibel_testRepositoryFolders.FormContentFolder(this);
                _textInfo = new RepoItemInfo(this, "Text", ".//form[#'sn-search-fields']/div[3]/input[@type='text']", ".//form[#'sn-search-fields']/div[3]/input[@type='text']", 30000, null, "a18192f5-dc6e-4488-9053-411b97b383de");
                _prof1Info = new RepoItemInfo(this, "Prof1", ".//form[#'sn-search-fields']/div[3]/select[@name='prof1']", ".//form[#'sn-search-fields']/div[3]/select[@name='prof1']", 30000, null, "060fccf2-dc40-4e6b-aece-a9c698f103e8");
                _scsearchInfo = new RepoItemInfo(this, "ScSearch", ".//button[#'sc-search']", ".//button[#'sc-search']", 30000, null, "889b8e7b-d693-486e-97d2-06d189a8106b");
                _borneInfo = new RepoItemInfo(this, "BORNE", ".//tr[#'row1']/?", "", 30000, null, "ff6d9bd8-8151-480a-b0e4-b1439e87a2ed");
                _contactInfo = new RepoItemInfo(this, "Contact", ".//tr[#'row1']/td[@title='Contact']", ".//tr[#'row1']/td[@title='Contact']", 30000, null, "5a903379-c105-42e6-9375-918fd2f64770");
                _containerfluidnomarginnopaddingscInfo = new RepoItemInfo(this, "ContainerFluidNoMarginNoPaddingSC", ".//div[#'applet1']/div[1]/div[2]", ".//div[#'applet1']/div[1]/div[2]", 30000, null, "3c830de5-9b0a-4593-9a6a-269707e5493b");
                _scsnkpksalesorderInfo = new RepoItemInfo(this, "ScSnkpkSalesorder", ".//button[#'sc-snkpk-salesorder']", ".//button[#'sc-snkpk-salesorder']", 30000, null, "e02f2b04-271a-40e6-8350-18911c809351");
                _scsearchtextInfo = new RepoItemInfo(this, "ScSearchtext", ".//input[#'sc_searchtext']", ".//input[#'sc_searchtext']", 30000, null, "7c3236dd-788d-40d6-a6bf-1a06d6c3c829");
                _scsearchbuttonInfo = new RepoItemInfo(this, "SCSearchbutton", ".//button[#'SC_searchbutton']", ".//button[#'SC_searchbutton']", 30000, null, "454a4d1e-453e-40e1-b18b-252ab1418578");
                _newqueenduali8360smartbedInfo = new RepoItemInfo(this, "NewQueenDualI8360SmartBed", ".//tbody[#'SC_Products']/?/?/td[@innertext>'New Queen Dual i8 360 Smart']", ".//tbody[#'SC_Products']/?/?/td[@innertext>'New Queen Dual i8 360 Smart']", 30000, null, "858309cc-7cd1-4477-ad22-e550e1ceaa16");
                _scaddtocartInfo = new RepoItemInfo(this, "SCAddToCart", ".//button[#'SC-Add-to-cart']", ".//button[#'SC-Add-to-cart']", 30000, null, "3503d903-b617-46d3-bccb-8721de74fee9");
                _nextInfo = new RepoItemInfo(this, "Next", ".//div[#'TopLevelButtons1']/div/div/div[2]/div[1]//button[@innertext='Next']", ".//div[#'TopLevelButtons1']//button[@innertext='Next']", 30000, null, "f292ea11-8d74-4a95-a3f4-38fc7a3bd12b");
                _next1Info = new RepoItemInfo(this, "Next1", ".//div[#'sc-accept-sku']/?/?/button[@innertext='Next']", ".//div[#'sc-accept-sku']/?/?/button[@innertext='Next']", 30000, null, "cce10096-09fd-4f0e-bf1f-b9ea492cb945");
                _scproceedInfo = new RepoItemInfo(this, "ScProceed", ".//button[#'sc-proceed']", ".//button[#'sc-proceed']", 30000, null, "eaacbcf3-27f1-41a6-a682-0d808b80ae02");
                _scshipvalidateorderInfo = new RepoItemInfo(this, "SCShipValidateOrder", ".//button[#'SC-ship-validate-order']", ".//button[#'SC-ship-validate-order']", 30000, null, "1f9217d2-c8d2-4955-bb26-d498c267f8cf");
                _scprocedpaymentsInfo = new RepoItemInfo(this, "SCProcedPayments", ".//button[#'SC-proced-payments']", ".//button[#'SC-proced-payments']", 30000, null, "84fa61f9-e14c-44f9-9f28-49e7cf9ef217");
                _cashpaymentInfo = new RepoItemInfo(this, "CashPayment", ".//div[#'cash-payment']", ".//div[#'cash-payment']", 30000, null, "e1257762-be86-4288-a2af-fcdd40e32911");
                _sccashInfo = new RepoItemInfo(this, "SCCash", ".//button[#'SC-cash']", ".//button[#'SC-cash']", 30000, null, "18a628f3-9a42-4dce-b718-118c66c70dd5");
                _orginalcolorscsopanelheadInfo = new RepoItemInfo(this, "OrginalColorSCSOPanelHead", ".//div[#'applet1']/div[1]/div[2]/div/div/div[1]", ".//div[#'applet1']/div[1]/div[2]/div/div/div[1]", 30000, null, "4f204865-1d27-4e1f-809e-7a756308aaf8");
                _paymentsInfo = new RepoItemInfo(this, "Payments", ".//div[#'SC-failed-payment-details']//p[@innertext='Payments']", ".//div[#'SC-failed-payment-details']//p[@innertext='Payments']", 30000, null, "2b79f0c0-3b06-4e54-b90c-e8947af56659");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("96f804d6-44be-4277-b3d2-f9a22f62d87f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("96f804d6-44be-4277-b3d2-f9a22f62d87f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("a18192f5-dc6e-4488-9053-411b97b383de")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("a18192f5-dc6e-4488-9053-411b97b383de")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Prof1 item.
            /// </summary>
            [RepositoryItem("060fccf2-dc40-4e6b-aece-a9c698f103e8")]
            public virtual Ranorex.SelectTag Prof1
            {
                get
                {
                    return _prof1Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Prof1 item info.
            /// </summary>
            [RepositoryItemInfo("060fccf2-dc40-4e6b-aece-a9c698f103e8")]
            public virtual RepoItemInfo Prof1Info
            {
                get
                {
                    return _prof1Info;
                }
            }

            /// <summary>
            /// The ScSearch item.
            /// </summary>
            [RepositoryItem("889b8e7b-d693-486e-97d2-06d189a8106b")]
            public virtual Ranorex.ButtonTag ScSearch
            {
                get
                {
                    return _scsearchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ScSearch item info.
            /// </summary>
            [RepositoryItemInfo("889b8e7b-d693-486e-97d2-06d189a8106b")]
            public virtual RepoItemInfo ScSearchInfo
            {
                get
                {
                    return _scsearchInfo;
                }
            }

            /// <summary>
            /// The BORNE item.
            /// </summary>
            [RepositoryItem("ff6d9bd8-8151-480a-b0e4-b1439e87a2ed")]
            public virtual Ranorex.Unknown BORNE
            {
                get
                {
                    return _borneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BORNE item info.
            /// </summary>
            [RepositoryItemInfo("ff6d9bd8-8151-480a-b0e4-b1439e87a2ed")]
            public virtual RepoItemInfo BORNEInfo
            {
                get
                {
                    return _borneInfo;
                }
            }

            /// <summary>
            /// The Contact item.
            /// </summary>
            [RepositoryItem("5a903379-c105-42e6-9375-918fd2f64770")]
            public virtual Ranorex.TdTag Contact
            {
                get
                {
                    return _contactInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Contact item info.
            /// </summary>
            [RepositoryItemInfo("5a903379-c105-42e6-9375-918fd2f64770")]
            public virtual RepoItemInfo ContactInfo
            {
                get
                {
                    return _contactInfo;
                }
            }

            /// <summary>
            /// The ContainerFluidNoMarginNoPaddingSC item.
            /// </summary>
            [RepositoryItem("3c830de5-9b0a-4593-9a6a-269707e5493b")]
            public virtual Ranorex.DivTag ContainerFluidNoMarginNoPaddingSC
            {
                get
                {
                    return _containerfluidnomarginnopaddingscInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContainerFluidNoMarginNoPaddingSC item info.
            /// </summary>
            [RepositoryItemInfo("3c830de5-9b0a-4593-9a6a-269707e5493b")]
            public virtual RepoItemInfo ContainerFluidNoMarginNoPaddingSCInfo
            {
                get
                {
                    return _containerfluidnomarginnopaddingscInfo;
                }
            }

            /// <summary>
            /// The ScSnkpkSalesorder item.
            /// </summary>
            [RepositoryItem("e02f2b04-271a-40e6-8350-18911c809351")]
            public virtual Ranorex.ButtonTag ScSnkpkSalesorder
            {
                get
                {
                    return _scsnkpksalesorderInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ScSnkpkSalesorder item info.
            /// </summary>
            [RepositoryItemInfo("e02f2b04-271a-40e6-8350-18911c809351")]
            public virtual RepoItemInfo ScSnkpkSalesorderInfo
            {
                get
                {
                    return _scsnkpksalesorderInfo;
                }
            }

            /// <summary>
            /// The ScSearchtext item.
            /// </summary>
            [RepositoryItem("7c3236dd-788d-40d6-a6bf-1a06d6c3c829")]
            public virtual Ranorex.InputTag ScSearchtext
            {
                get
                {
                    return _scsearchtextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ScSearchtext item info.
            /// </summary>
            [RepositoryItemInfo("7c3236dd-788d-40d6-a6bf-1a06d6c3c829")]
            public virtual RepoItemInfo ScSearchtextInfo
            {
                get
                {
                    return _scsearchtextInfo;
                }
            }

            /// <summary>
            /// The SCSearchbutton item.
            /// </summary>
            [RepositoryItem("454a4d1e-453e-40e1-b18b-252ab1418578")]
            public virtual Ranorex.ButtonTag SCSearchbutton
            {
                get
                {
                    return _scsearchbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SCSearchbutton item info.
            /// </summary>
            [RepositoryItemInfo("454a4d1e-453e-40e1-b18b-252ab1418578")]
            public virtual RepoItemInfo SCSearchbuttonInfo
            {
                get
                {
                    return _scsearchbuttonInfo;
                }
            }

            /// <summary>
            /// The NewQueenDualI8360SmartBed item.
            /// </summary>
            [RepositoryItem("858309cc-7cd1-4477-ad22-e550e1ceaa16")]
            public virtual Ranorex.TdTag NewQueenDualI8360SmartBed
            {
                get
                {
                    return _newqueenduali8360smartbedInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The NewQueenDualI8360SmartBed item info.
            /// </summary>
            [RepositoryItemInfo("858309cc-7cd1-4477-ad22-e550e1ceaa16")]
            public virtual RepoItemInfo NewQueenDualI8360SmartBedInfo
            {
                get
                {
                    return _newqueenduali8360smartbedInfo;
                }
            }

            /// <summary>
            /// The SCAddToCart item.
            /// </summary>
            [RepositoryItem("3503d903-b617-46d3-bccb-8721de74fee9")]
            public virtual Ranorex.ButtonTag SCAddToCart
            {
                get
                {
                    return _scaddtocartInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SCAddToCart item info.
            /// </summary>
            [RepositoryItemInfo("3503d903-b617-46d3-bccb-8721de74fee9")]
            public virtual RepoItemInfo SCAddToCartInfo
            {
                get
                {
                    return _scaddtocartInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("f292ea11-8d74-4a95-a3f4-38fc7a3bd12b")]
            public virtual Ranorex.ButtonTag Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("f292ea11-8d74-4a95-a3f4-38fc7a3bd12b")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The Next1 item.
            /// </summary>
            [RepositoryItem("cce10096-09fd-4f0e-bf1f-b9ea492cb945")]
            public virtual Ranorex.ButtonTag Next1
            {
                get
                {
                    return _next1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Next1 item info.
            /// </summary>
            [RepositoryItemInfo("cce10096-09fd-4f0e-bf1f-b9ea492cb945")]
            public virtual RepoItemInfo Next1Info
            {
                get
                {
                    return _next1Info;
                }
            }

            /// <summary>
            /// The ScProceed item.
            /// </summary>
            [RepositoryItem("eaacbcf3-27f1-41a6-a682-0d808b80ae02")]
            public virtual Ranorex.ButtonTag ScProceed
            {
                get
                {
                    return _scproceedInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ScProceed item info.
            /// </summary>
            [RepositoryItemInfo("eaacbcf3-27f1-41a6-a682-0d808b80ae02")]
            public virtual RepoItemInfo ScProceedInfo
            {
                get
                {
                    return _scproceedInfo;
                }
            }

            /// <summary>
            /// The SCShipValidateOrder item.
            /// </summary>
            [RepositoryItem("1f9217d2-c8d2-4955-bb26-d498c267f8cf")]
            public virtual Ranorex.ButtonTag SCShipValidateOrder
            {
                get
                {
                    return _scshipvalidateorderInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SCShipValidateOrder item info.
            /// </summary>
            [RepositoryItemInfo("1f9217d2-c8d2-4955-bb26-d498c267f8cf")]
            public virtual RepoItemInfo SCShipValidateOrderInfo
            {
                get
                {
                    return _scshipvalidateorderInfo;
                }
            }

            /// <summary>
            /// The SCProcedPayments item.
            /// </summary>
            [RepositoryItem("84fa61f9-e14c-44f9-9f28-49e7cf9ef217")]
            public virtual Ranorex.ButtonTag SCProcedPayments
            {
                get
                {
                    return _scprocedpaymentsInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SCProcedPayments item info.
            /// </summary>
            [RepositoryItemInfo("84fa61f9-e14c-44f9-9f28-49e7cf9ef217")]
            public virtual RepoItemInfo SCProcedPaymentsInfo
            {
                get
                {
                    return _scprocedpaymentsInfo;
                }
            }

            /// <summary>
            /// The CashPayment item.
            /// </summary>
            [RepositoryItem("e1257762-be86-4288-a2af-fcdd40e32911")]
            public virtual Ranorex.DivTag CashPayment
            {
                get
                {
                    return _cashpaymentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CashPayment item info.
            /// </summary>
            [RepositoryItemInfo("e1257762-be86-4288-a2af-fcdd40e32911")]
            public virtual RepoItemInfo CashPaymentInfo
            {
                get
                {
                    return _cashpaymentInfo;
                }
            }

            /// <summary>
            /// The SCCash item.
            /// </summary>
            [RepositoryItem("18a628f3-9a42-4dce-b718-118c66c70dd5")]
            public virtual Ranorex.ButtonTag SCCash
            {
                get
                {
                    return _sccashInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SCCash item info.
            /// </summary>
            [RepositoryItemInfo("18a628f3-9a42-4dce-b718-118c66c70dd5")]
            public virtual RepoItemInfo SCCashInfo
            {
                get
                {
                    return _sccashInfo;
                }
            }

            /// <summary>
            /// The OrginalColorSCSOPanelHead item.
            /// </summary>
            [RepositoryItem("4f204865-1d27-4e1f-809e-7a756308aaf8")]
            public virtual Ranorex.DivTag OrginalColorSCSOPanelHead
            {
                get
                {
                    return _orginalcolorscsopanelheadInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The OrginalColorSCSOPanelHead item info.
            /// </summary>
            [RepositoryItemInfo("4f204865-1d27-4e1f-809e-7a756308aaf8")]
            public virtual RepoItemInfo OrginalColorSCSOPanelHeadInfo
            {
                get
                {
                    return _orginalcolorscsopanelheadInfo;
                }
            }

            /// <summary>
            /// The Payments item.
            /// </summary>
            [RepositoryItem("2b79f0c0-3b06-4e54-b90c-e8947af56659")]
            public virtual Ranorex.PTag Payments
            {
                get
                {
                    return _paymentsInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Payments item info.
            /// </summary>
            [RepositoryItemInfo("2b79f0c0-3b06-4e54-b90c-e8947af56659")]
            public virtual RepoItemInfo PaymentsInfo
            {
                get
                {
                    return _paymentsInfo;
                }
            }

            /// <summary>
            /// The FormContent folder.
            /// </summary>
            [RepositoryFolder("ba716ca4-9c07-4113-8a86-368f149b7827")]
            public virtual seibel_testRepositoryFolders.FormContentFolder FormContent
            {
                get { return _formcontent; }
            }
        }

        /// <summary>
        /// The FormContentFolder folder.
        /// </summary>
        [RepositoryFolder("ba716ca4-9c07-4113-8a86-368f149b7827")]
        public partial class FormContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _swepasswordInfo;
            RepoItemInfo _sweusernameInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new FormContent  folder.
            /// </summary>
            public FormContentFolder(RepoGenBaseFolder parentFolder) :
                    base("FormContent", ".//div[#'formContent']", parentFolder, 30000, null, false, "ba716ca4-9c07-4113-8a86-368f149b7827", "")
            {
                _swepasswordInfo = new RepoItemInfo(this, "SWEPassword", ".//input[@title='Password']", ".//input[@title='Password']", 30000, null, "897e4572-42ce-490b-814f-c43852bba997");
                _sweusernameInfo = new RepoItemInfo(this, "SWEUserName", ".//input[@title='User ID']", ".//input[@title='User ID']", 30000, null, "f49809b4-47fa-4ee7-ab30-0a25143dde03");
                _loginInfo = new RepoItemInfo(this, "Login", "?/?/a[@innertext='Login']", "?/?/a[@innertext='Login']", 30000, null, "44568dcc-6368-4bf6-8806-960c8c39562e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba716ca4-9c07-4113-8a86-368f149b7827")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba716ca4-9c07-4113-8a86-368f149b7827")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SWEPassword item.
            /// </summary>
            [RepositoryItem("897e4572-42ce-490b-814f-c43852bba997")]
            public virtual Ranorex.InputTag SWEPassword
            {
                get
                {
                    return _swepasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SWEPassword item info.
            /// </summary>
            [RepositoryItemInfo("897e4572-42ce-490b-814f-c43852bba997")]
            public virtual RepoItemInfo SWEPasswordInfo
            {
                get
                {
                    return _swepasswordInfo;
                }
            }

            /// <summary>
            /// The SWEUserName item.
            /// </summary>
            [RepositoryItem("f49809b4-47fa-4ee7-ab30-0a25143dde03")]
            public virtual Ranorex.InputTag SWEUserName
            {
                get
                {
                    return _sweusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SWEUserName item info.
            /// </summary>
            [RepositoryItemInfo("f49809b4-47fa-4ee7-ab30-0a25143dde03")]
            public virtual RepoItemInfo SWEUserNameInfo
            {
                get
                {
                    return _sweusernameInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("44568dcc-6368-4bf6-8806-960c8c39562e")]
            public virtual Ranorex.ATag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("44568dcc-6368-4bf6-8806-960c8c39562e")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The SiebelCallCenterWorkMicrosoftEdAppFolder folder.
        /// </summary>
        [RepositoryFolder("769ac0b0-efee-4a3b-8b19-6d12e6fcb4fe")]
        public partial class SiebelCallCenterWorkMicrosoftEdAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new SiebelCallCenterWorkMicrosoftEd  folder.
            /// </summary>
            public SiebelCallCenterWorkMicrosoftEdAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SiebelCallCenterWorkMicrosoftEd", "/form[@title>'Siebel Call Center - Work']", parentFolder, 30000, null, true, "769ac0b0-efee-4a3b-8b19-6d12e6fcb4fe", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("769ac0b0-efee-4a3b-8b19-6d12e6fcb4fe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("769ac0b0-efee-4a3b-8b19-6d12e6fcb4fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LineItemsWorkMicrosoftEdgeAppFolder folder.
        /// </summary>
        [RepositoryFolder("041fe668-8eda-49a8-b132-139bfecc127a")]
        public partial class LineItemsWorkMicrosoftEdgeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new LineItemsWorkMicrosoftEdge  folder.
            /// </summary>
            public LineItemsWorkMicrosoftEdgeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LineItemsWorkMicrosoftEdge", "/form[@title>'Line Items - Work - Microsoft​']", parentFolder, 30000, null, true, "041fe668-8eda-49a8-b132-139bfecc127a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("041fe668-8eda-49a8-b132-139bfecc127a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("041fe668-8eda-49a8-b132-139bfecc127a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LineItemsAnd1MorePageWorkMicrAppFolder folder.
        /// </summary>
        [RepositoryFolder("2901aa33-2dec-4a92-8c06-5b9e824cacf0")]
        public partial class LineItemsAnd1MorePageWorkMicrAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nativeviewhostInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new LineItemsAnd1MorePageWorkMicr  folder.
            /// </summary>
            public LineItemsAnd1MorePageWorkMicrAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LineItemsAnd1MorePageWorkMicr", "/form[@title>'Line Items and 1 more page']", parentFolder, 30000, null, true, "2901aa33-2dec-4a92-8c06-5b9e824cacf0", "")
            {
                _nativeviewhostInfo = new RepoItemInfo(this, "NativeViewHost", "container[@name>'Line Items - Microsoft Ed']/container[@name='Microsoft Edge']//container[@classname='SidebarContentsSplitView']//text[@automationid='view_1053']/container[@classname='NativeViewHost']", ".//text[@automationid='view_1053']/container[@classname='NativeViewHost']", 30000, null, "0e9b2ebb-81c2-40b6-aae2-b3f14a03a074");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@name>'crmappstst1.comfort.com:4443']/form[@name>'crmappstst1.comfort.com:4443']//button[@name='OK']", ".//button[@name='OK']", 30000, null, "3a39481e-47fe-4a30-92bc-bb680baa9d42");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2901aa33-2dec-4a92-8c06-5b9e824cacf0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2901aa33-2dec-4a92-8c06-5b9e824cacf0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NativeViewHost item.
            /// </summary>
            [RepositoryItem("0e9b2ebb-81c2-40b6-aae2-b3f14a03a074")]
            public virtual Ranorex.Container NativeViewHost
            {
                get
                {
                    return _nativeviewhostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NativeViewHost item info.
            /// </summary>
            [RepositoryItemInfo("0e9b2ebb-81c2-40b6-aae2-b3f14a03a074")]
            public virtual RepoItemInfo NativeViewHostInfo
            {
                get
                {
                    return _nativeviewhostInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("3a39481e-47fe-4a30-92bc-bb680baa9d42")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("3a39481e-47fe-4a30-92bc-bb680baa9d42")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
